### ISSUE TITLE
MDM reshape images to square, even if they are rectangular

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mdm#151]
Profile pictures are streched to rectangle. Bug?

**Comment by clefebvre** [comment]
Which theme?

**Comment by Yanpas** [comment]
Theme is GTK. Grab it. I was to compress this snake and convert from png to jpg, other way MDM doesn't display anything ...
![default face](https://cloud.githubusercontent.com/assets/7345761/10118167/a2d1c028-647a-11e5-9289-c6652fd1820f.jpg)

**Comment by rpremuz** [comment]
I'd just like to comment that since Linux Mint 17.1 you can get the preview of the login screen by clicking a button in the Login Window Preferences (mdmsetup):

![screenshot from 2015-10-18 13 50 13](https://cloud.githubusercontent.com/assets/5261871/10563950/8c6731b6-759f-11e5-8a10-d12a0482a60b.png)

**Comment by Yanpas** [comment]
@rpremuz avatars in preview mode do not work
