### ISSUE TITLE
No indicator of keyboard layout

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mdm#154]
Im using 2.0 mdm, basic gtk theme

**Comment by jounathaen** [comment]
For me it seems that there is not even the possibility to change the layouts.
I've a DE Layout on my laptop, but an US Layout on my external keyboard. After login it is easy to switch layout in Cinnamon but I ALWAYS misspell my Password :-D
If there is the possibility (e.g. using a shortcut like ALT+CAPS) please tell me, otherwise I'd suggest this feature!
Best Regards

**Comment by clefebvre** [comment]
This commit now explicitly sets the layout https://github.com/linuxmint/mdm/commit/a293167340624021e1b379118a647a97da9dd550

In any case, even without this, you should be able to configure your /etc/default/keyboard. In there you can define multiple layouts (for instance "de, us") and a switch key (for instance XKBOPTIONS="grp:alt_shift_toggle" to use ALT+SHIFT).

**Comment by jounathaen** [comment]
Late reply, but:
/etc/default/keyboard works, thanks! But I still have to change the layout after the login once more.
Would be nice, if mdm hands over the layout, or cinnamon reads the setting somehow, so that you only have to "alt+shift" in the login screen, and have the layout changed for the cinnamon session as well.
Very best regards!
Jounathaen

**Comment by jounathaen** [comment]
And another "Bug": 
The keyboard layout of the Lock Screen does not match the layout of the current cinnamon session.
I can change it with "alt+shift"
