### ISSUE TITLE
Setting umask at  /etc/profile  for all users is not respected

### ISSUE THREAD

**Issue by FBachofner** [linuxmint/mdm#190]
Mint 18 (and earlier) does not respect the **_umask_** setting in the file  `/etc/profile`  (which is supposed to set umask for all users of the system)

Discussion and workaround available at the Mint forums:
https://forums.linuxmint.com/viewtopic.php?p=1236385

**Comment by clefebvre** [comment]
Hi @FBachofner,

I think it's due to https://github.com/linuxmint/mdm/blob/master/daemon/slave.c#L3006

**Comment by clefebvre** [comment]
You can try and move that line up, before the presession script is run.

**Comment by testbird** [comment]
The umask is set by the pam login system (consistently across displays, shells, remote logins, ...).

There should't be any hardcoded default umask setting at all, so you can simply comment it out or remove it completely.

(For specific writes the umask may of course be set explicitly, if appropriate, and then reverted to the priorly saved old value, instead of a hard coded value. May this be the error that was originally made when this line was introduced?)

**Comment by testbird** [comment]
Related ubuntu bugs: https://wiki.ubuntu.com/MultiUserManagement

**Comment by xenopeek** [comment]
Related to #123.
