### ISSUE TITLE
No avatar if using encrypted home directory

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/mdm#78]
If a user has an encrypted home directory then they can't have an avatar apparently, not even one of the preset cats or astronaut ones. I don't have an immediately genius way around this, at least not one that would work with every desktop environment. Perhaps on cinnamon the user avatar selector could transfer just an avatar outside of /home.

**Comment by clefebvre** [comment]
Hi, these issues are fixed in master (they'll be released as part of MDM 2.0).

- AccountsService was supported but only when using a non-system avatar (i.e. MDM read /var/lib/AccountsService/icons but didn't parse /var/lib/AccountsService/users).
- AccountsService was only used in mdmgreeter and mdmlogin, not in mdmwebkit.
- As tobami mentioned there were issues with file permission checks as well.
